/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/main_room.glb -k 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/main_room.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Fish_Bowl_Glass"
        geometry={nodes.Fish_Bowl_Glass.geometry}
        material={nodes.Fish_Bowl_Glass.material}
        position={[-0.707, 1.246, 1.154]}
      />
      <mesh
        name="Computer_Glass"
        geometry={nodes.Computer_Glass.geometry}
        material={nodes.Computer_Glass.material}
        position={[-2.2, 3.811, -3.193]}
      />
      <mesh
        name="Screen"
        geometry={nodes.Screen.geometry}
        material={nodes.Screen.material}
        position={[-2.855, 4.492, -1.492]}
      />
      <mesh
        name="Fish_Bowl_Water"
        geometry={nodes.Fish_Bowl_Water.geometry}
        material={nodes.Fish_Bowl_Water.material}
        position={[-0.707, 1.246, 1.154]}
      />
      <mesh
        name="About_Button_Third_Raycaster_Pointer_Hover"
        geometry={nodes.About_Button_Third_Raycaster_Pointer_Hover.geometry}
        material={nodes.About_Button_Third_Raycaster_Pointer_Hover.material}
        position={[-3.518, 5.461, 3.094]}
        rotation={[0, 1.526, -1.506]}
      />
      <mesh
        name="Contact_Button_Third_Raycaster_Pointer_Hover"
        geometry={nodes.Contact_Button_Third_Raycaster_Pointer_Hover.geometry}
        material={nodes.Contact_Button_Third_Raycaster_Pointer_Hover.material}
        position={[-3.518, 3.832, 3.093]}
        rotation={[0, 1.526, -1.631]}
      />
      <mesh
        name="My_Work_Button_Third_Raycaster_Pointer_Hover"
        geometry={nodes.My_Work_Button_Third_Raycaster_Pointer_Hover.geometry}
        material={nodes.My_Work_Button_Third_Raycaster_Pointer_Hover.material}
        position={[-3.518, 4.648, 3.093]}
        rotation={[-0.873, 1.506, -0.76]}
      />
      <mesh
        name="Hanging_Plank_1_Third"
        geometry={nodes.Hanging_Plank_1_Third.geometry}
        material={nodes.Hanging_Plank_1_Third.material}
        position={[-3.56, 6.371, 2.112]}
        rotation={[-1.571, -1.557, -Math.PI]}
      />
      <mesh
        name="Hanging_Plank_2_Third"
        geometry={nodes.Hanging_Plank_2_Third.geometry}
        material={nodes.Hanging_Plank_2_Third.material}
        position={[-3.595, 6.29, 3.08]}
        rotation={[0, 1.526, 0]}
      />
      <mesh
        name="Boba_Plushie_Fourth_Raycaster_Hover"
        geometry={nodes.Boba_Plushie_Fourth_Raycaster_Hover.geometry}
        material={nodes.Boba_Plushie_Fourth_Raycaster_Hover.material}
        position={[-2.921, 5.592, -3.978]}
        rotation={[0.003, 0.357, 0.032]}
      />
      <mesh
        name="GitHub_Fourth_Raycaster_Pointer_Hover"
        geometry={nodes.GitHub_Fourth_Raycaster_Pointer_Hover.geometry}
        material={nodes.GitHub_Fourth_Raycaster_Pointer_Hover.material}
        position={[-2.31, 5.619, -3.988]}
        rotation={[1.256, 0, 0]}
      />
      <mesh
        name="Twitter_Fourth_Raycaster_Pointer_Hover"
        geometry={nodes.Twitter_Fourth_Raycaster_Pointer_Hover.geometry}
        material={nodes.Twitter_Fourth_Raycaster_Pointer_Hover.material}
        position={[-1.092, 5.625, -3.992]}
        rotation={[1.256, 0, 0]}
      />
      <mesh
        name="YouTube_Fourth_Raycaster_Pointer_Hover"
        geometry={nodes.YouTube_Fourth_Raycaster_Pointer_Hover.geometry}
        material={nodes.YouTube_Fourth_Raycaster_Pointer_Hover.material}
        position={[-1.694, 5.621, -3.989]}
        rotation={[1.256, 0, 0]}
      />
      <mesh
        name="Computer_Fan_1_Fourth_Raycaster"
        geometry={nodes.Computer_Fan_1_Fourth_Raycaster.geometry}
        material={nodes.Computer_Fan_1_Fourth_Raycaster.material}
        position={[-2.482, 3.671, -3.226]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Computer_Fan_2_Fourth_Raycaster"
        geometry={nodes.Computer_Fan_2_Fourth_Raycaster.geometry}
        material={nodes.Computer_Fan_2_Fourth_Raycaster.material}
        position={[-3.074, 3.756, -3.564]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        name="Computer_Fan_3_Fourth_Raycaster"
        geometry={nodes.Computer_Fan_3_Fourth_Raycaster.geometry}
        material={nodes.Computer_Fan_3_Fourth_Raycaster.material}
        position={[-2.144, 3.671, -3.226]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Computer_Fan_4_Fourth_Raycaster"
        geometry={nodes.Computer_Fan_4_Fourth_Raycaster.geometry}
        material={nodes.Computer_Fan_4_Fourth_Raycaster.material}
        position={[-3.074, 4.095, -3.564]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        name="Computer_Fan_5_Fourth_Raycaster"
        geometry={nodes.Computer_Fan_5_Fourth_Raycaster.geometry}
        material={nodes.Computer_Fan_5_Fourth_Raycaster.material}
        position={[-1.804, 3.671, -3.226]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Chair_Top_Fourth"
        geometry={nodes.Chair_Top_Fourth.geometry}
        material={nodes.Chair_Top_Fourth.material}
        position={[-0.816, 1.806, -1.82]}
      />
      <mesh
        name="Flower_1_Fourth_Hover_Raycaster"
        geometry={nodes.Flower_1_Fourth_Hover_Raycaster.geometry}
        material={nodes.Flower_1_Fourth_Hover_Raycaster.material}
        position={[-2.811, 3.36, 0.53]}
      />
      <mesh
        name="Flower_2_Fourth_Hover_Raycaster"
        geometry={nodes.Flower_2_Fourth_Hover_Raycaster.geometry}
        material={nodes.Flower_2_Fourth_Hover_Raycaster.material}
        position={[-2.936, 3.401, 0.563]}
      />
      <mesh
        name="Flower_3_Fourth_Hover_Raycaster"
        geometry={nodes.Flower_3_Fourth_Hover_Raycaster.geometry}
        material={nodes.Flower_3_Fourth_Hover_Raycaster.material}
        position={[-2.911, 3.363, 0.4]}
      />
      <mesh
        name="Kirby_Third_Hover_Raycaster"
        geometry={nodes.Kirby_Third_Hover_Raycaster.geometry}
        material={nodes.Kirby_Third_Hover_Raycaster.material}
        position={[1.497, 0.562, -2.029]}
      />
      <mesh
        name="Fish_Fourth_Hover_Raycaster"
        geometry={nodes.Fish_Fourth_Hover_Raycaster.geometry}
        material={nodes.Fish_Fourth_Hover_Raycaster.material}
        position={[-0.759, 1.655, 1.184]}
      />
      <mesh
        name="Hour_Hand_First"
        geometry={nodes.Hour_Hand_First.geometry}
        material={nodes.Hour_Hand_First.material}
        position={[-3.243, 6.39, -0.731]}
      />
      <mesh
        name="Minute_Hand_First"
        geometry={nodes.Minute_Hand_First.geometry}
        material={nodes.Minute_Hand_First.material}
        position={[-3.243, 6.39, -0.731]}
      />
      <mesh
        name="Lamp_First_Hover_Raycaster"
        geometry={nodes.Lamp_First_Hover_Raycaster.geometry}
        material={nodes.Lamp_First_Hover_Raycaster.material}
        position={[-0.775, 0.526, -3.196]}
      />
      <mesh
        name="Flower_4_Fourth_Raycaster_Hover"
        geometry={nodes.Flower_4_Fourth_Raycaster_Hover.geometry}
        material={nodes.Flower_4_Fourth_Raycaster_Hover.material}
        position={[-2.905, 3.992, 1.528]}
      />
      <mesh
        name="Flower_5_Fourth_Raycaster_Hover"
        geometry={nodes.Flower_5_Fourth_Raycaster_Hover.geometry}
        material={nodes.Flower_5_Fourth_Raycaster_Hover.material}
        position={[-2.866, 4.036, 1.467]}
      />
      <mesh
        name="Egg_1_Fourth_Hover_Raycaster"
        geometry={nodes.Egg_1_Fourth_Hover_Raycaster.geometry}
        material={nodes.Egg_1_Fourth_Hover_Raycaster.material}
        position={[-3.066, 6.566, -2.284]}
      />
      <mesh
        name="Egg_2_Fourth_Hover_Raycaster"
        geometry={nodes.Egg_2_Fourth_Hover_Raycaster.geometry}
        material={nodes.Egg_2_Fourth_Hover_Raycaster.material}
        position={[-2.996, 6.566, -2.409]}
      />
      <mesh
        name="Egg_3_Fourth_Hover_Raycaster"
        geometry={nodes.Egg_3_Fourth_Hover_Raycaster.geometry}
        material={nodes.Egg_3_Fourth_Hover_Raycaster.material}
        position={[-3.135, 6.566, -2.411]}
      />
      <mesh
        name="Pencil_1_Fourth_Hover_Raycaster"
        geometry={nodes.Pencil_1_Fourth_Hover_Raycaster.geometry}
        material={nodes.Pencil_1_Fourth_Hover_Raycaster.material}
        position={[-2.677, 2.864, 1.611]}
      />
      <mesh
        name="Pencil_2_Fourth_Hover_Raycaster"
        geometry={nodes.Pencil_2_Fourth_Hover_Raycaster.geometry}
        material={nodes.Pencil_2_Fourth_Hover_Raycaster.material}
        position={[-2.712, 2.858, 1.568]}
      />
      <mesh
        name="Pencil_3_Fourth_Hover_Raycaster"
        geometry={nodes.Pencil_3_Fourth_Hover_Raycaster.geometry}
        material={nodes.Pencil_3_Fourth_Hover_Raycaster.material}
        position={[-2.653, 2.862, 1.54]}
      />
      <mesh
        name="A#1_Key_Pointer_Raycaster_Third"
        geometry={nodes["A#1_Key_Pointer_Raycaster_Third"].geometry}
        material={nodes["A#1_Key_Pointer_Raycaster_Third"].material}
        position={[0.662, 2.743, -3.616]}
      />
      <mesh
        name="A#2_Key_Pointer_Raycaster_Third"
        geometry={nodes["A#2_Key_Pointer_Raycaster_Third"].geometry}
        material={nodes["A#2_Key_Pointer_Raycaster_Third"].material}
        position={[2.14, 2.743, -3.616]}
      />
      <mesh
        name="A1_Key_Pointer_Raycaster_Third"
        geometry={nodes.A1_Key_Pointer_Raycaster_Third.geometry}
        material={nodes.A1_Key_Pointer_Raycaster_Third.material}
        position={[0.553, 2.671, -3.617]}
      />
      <mesh
        name="A2_Key_Pointer_Raycaster_Third"
        geometry={nodes.A2_Key_Pointer_Raycaster_Third.geometry}
        material={nodes.A2_Key_Pointer_Raycaster_Third.material}
        position={[2.038, 2.671, -3.617]}
      />
      <mesh
        name="B1_Key_Pointer_Raycaster_Third"
        geometry={nodes.B1_Key_Pointer_Raycaster_Third.geometry}
        material={nodes.B1_Key_Pointer_Raycaster_Third.material}
        position={[0.765, 2.671, -3.617]}
      />
      <mesh
        name="B2_Key_Pointer_Raycaster_Third"
        geometry={nodes.B2_Key_Pointer_Raycaster_Third.geometry}
        material={nodes.B2_Key_Pointer_Raycaster_Third.material}
        position={[2.25, 2.671, -3.617]}
      />
      <mesh
        name="C#1_Key_Pointer_Raycaster_Third"
        geometry={nodes["C#1_Key_Pointer_Raycaster_Third"].geometry}
        material={nodes["C#1_Key_Pointer_Raycaster_Third"].material}
        position={[-0.404, 2.743, -3.616]}
      />
      <mesh
        name="C#2_Key_Pointer_Raycaster_Third"
        geometry={nodes["C#2_Key_Pointer_Raycaster_Third"].geometry}
        material={nodes["C#2_Key_Pointer_Raycaster_Third"].material}
        position={[1.074, 2.743, -3.616]}
      />
      <mesh
        name="C1_Key_Pointer_Raycaster_Third"
        geometry={nodes.C1_Key_Pointer_Raycaster_Third.geometry}
        material={nodes.C1_Key_Pointer_Raycaster_Third.material}
        position={[-0.508, 2.671, -3.617]}
      />
      <mesh
        name="C2_Key_Pointer_Raycaster_Third"
        geometry={nodes.C2_Key_Pointer_Raycaster_Third.geometry}
        material={nodes.C2_Key_Pointer_Raycaster_Third.material}
        position={[0.977, 2.671, -3.617]}
      />
      <mesh
        name="D#1_Key_Pointer_Raycaster_Third"
        geometry={nodes["D#1_Key_Pointer_Raycaster_Third"].geometry}
        material={nodes["D#1_Key_Pointer_Raycaster_Third"].material}
        position={[-0.19, 2.743, -3.616]}
      />
      <mesh
        name="D#2_Key_Pointer_Raycaster_Third"
        geometry={nodes["D#2_Key_Pointer_Raycaster_Third"].geometry}
        material={nodes["D#2_Key_Pointer_Raycaster_Third"].material}
        position={[1.288, 2.743, -3.616]}
      />
      <mesh
        name="D1_Key_Pointer_Raycaster_Third"
        geometry={nodes.D1_Key_Pointer_Raycaster_Third.geometry}
        material={nodes.D1_Key_Pointer_Raycaster_Third.material}
        position={[-0.296, 2.671, -3.617]}
      />
      <mesh
        name="D2_Key_Pointer_Raycaster_Third"
        geometry={nodes.D2_Key_Pointer_Raycaster_Third.geometry}
        material={nodes.D2_Key_Pointer_Raycaster_Third.material}
        position={[1.189, 2.671, -3.617]}
      />
      <mesh
        name="E1_Key_Pointer_Raycaster_Third"
        geometry={nodes.E1_Key_Pointer_Raycaster_Third.geometry}
        material={nodes.E1_Key_Pointer_Raycaster_Third.material}
        position={[-0.083, 2.671, -3.617]}
      />
      <mesh
        name="E2_Key_Pointer_Raycaster_Third"
        geometry={nodes.E2_Key_Pointer_Raycaster_Third.geometry}
        material={nodes.E2_Key_Pointer_Raycaster_Third.material}
        position={[1.402, 2.671, -3.617]}
      />
      <mesh
        name="F#1_Key_Pointer_Raycaster_Third"
        geometry={nodes["F#1_Key_Pointer_Raycaster_Third"].geometry}
        material={nodes["F#1_Key_Pointer_Raycaster_Third"].material}
        position={[0.234, 2.743, -3.616]}
      />
      <mesh
        name="F#2_Key_Pointer_Raycaster_Third"
        geometry={nodes["F#2_Key_Pointer_Raycaster_Third"].geometry}
        material={nodes["F#2_Key_Pointer_Raycaster_Third"].material}
        position={[1.712, 2.743, -3.616]}
      />
      <mesh
        name="F1_Key_Pointer_Raycaster_Third"
        geometry={nodes.F1_Key_Pointer_Raycaster_Third.geometry}
        material={nodes.F1_Key_Pointer_Raycaster_Third.material}
        position={[0.129, 2.671, -3.617]}
      />
      <mesh
        name="F2_Key_Pointer_Raycaster_Third"
        geometry={nodes.F2_Key_Pointer_Raycaster_Third.geometry}
        material={nodes.F2_Key_Pointer_Raycaster_Third.material}
        position={[1.614, 2.671, -3.617]}
      />
      <mesh
        name="G#1_Key_Pointer_Raycaster_Third"
        geometry={nodes["G#1_Key_Pointer_Raycaster_Third"].geometry}
        material={nodes["G#1_Key_Pointer_Raycaster_Third"].material}
        position={[0.448, 2.743, -3.616]}
      />
      <mesh
        name="G#2_Key_Pointer_Raycaster_Third"
        geometry={nodes["G#2_Key_Pointer_Raycaster_Third"].geometry}
        material={nodes["G#2_Key_Pointer_Raycaster_Third"].material}
        position={[1.926, 2.743, -3.616]}
      />
      <mesh
        name="G1_Key_Pointer_Raycaster_Third"
        geometry={nodes.G1_Key_Pointer_Raycaster_Third.geometry}
        material={nodes.G1_Key_Pointer_Raycaster_Third.material}
        position={[0.341, 2.671, -3.617]}
      />
      <mesh
        name="G2_Key_Pointer_Raycaster_Third"
        geometry={nodes.G2_Key_Pointer_Raycaster_Third.geometry}
        material={nodes.G2_Key_Pointer_Raycaster_Third.material}
        position={[1.826, 2.671, -3.617]}
      />
      <mesh
        name="Name_Platform_Third"
        geometry={nodes.Name_Platform_Third.geometry}
        material={nodes.Name_Platform_Third.material}
        position={[1.318, 3.376, -4.219]}
      />
      <mesh
        name="Bulb_1_Fourth_Raycaster_Hover_2"
        geometry={nodes.Bulb_1_Fourth_Raycaster_Hover_2.geometry}
        material={nodes.Bulb_1_Fourth_Raycaster_Hover_2.material}
        position={[-2.846, 5.621, 0.33]}
      />
      <mesh
        name="Bulb_2_Fourth_Raycaster_Hover_2"
        geometry={nodes.Bulb_2_Fourth_Raycaster_Hover_2.geometry}
        material={nodes.Bulb_2_Fourth_Raycaster_Hover_2.material}
        position={[-2.787, 5.583, -0.163]}
      />
      <mesh
        name="Bulb_3_Fourth_Raycaster_Hover_2"
        geometry={nodes.Bulb_3_Fourth_Raycaster_Hover_2.geometry}
        material={nodes.Bulb_3_Fourth_Raycaster_Hover_2.material}
        position={[-2.772, 5.642, -0.66]}
      />
      <mesh
        name="Bulb_4_Fourth_Raycaster_Hover_2"
        geometry={nodes.Bulb_4_Fourth_Raycaster_Hover_2.geometry}
        material={nodes.Bulb_4_Fourth_Raycaster_Hover_2.material}
        position={[-2.796, 5.81, -1.13]}
      />
      <mesh
        name="Bulb_5_Fourth_Raycaster_Hover_2"
        geometry={nodes.Bulb_5_Fourth_Raycaster_Hover_2.geometry}
        material={nodes.Bulb_5_Fourth_Raycaster_Hover_2.material}
        position={[-2.873, 6.01, -1.574]}
      />
      <mesh
        name="Bulb_6_Fourth_Raycaster_Hover_2"
        geometry={nodes.Bulb_6_Fourth_Raycaster_Hover_2.geometry}
        material={nodes.Bulb_6_Fourth_Raycaster_Hover_2.material}
        position={[-3.119, 6.189, -2.499]}
      />
      <mesh
        name="Bulb_7_Fourth_Raycaster_Hover_2"
        geometry={nodes.Bulb_7_Fourth_Raycaster_Hover_2.geometry}
        material={nodes.Bulb_7_Fourth_Raycaster_Hover_2.material}
        position={[-2.85, 5.862, -2.681]}
      />
      <mesh
        name="Bulb_8_Fourth_Raycaster_Hover_2"
        geometry={nodes.Bulb_8_Fourth_Raycaster_Hover_2.geometry}
        material={nodes.Bulb_8_Fourth_Raycaster_Hover_2.material}
        position={[-2.603, 5.607, -3.027]}
      />
      <mesh
        name="Bulb_9_Fourth_Raycaster_Hover_2"
        geometry={nodes.Bulb_9_Fourth_Raycaster_Hover_2.geometry}
        material={nodes.Bulb_9_Fourth_Raycaster_Hover_2.material}
        position={[-2.443, 5.5, -3.48]}
      />
      <mesh
        name="Slipper_1_Fourth_Hover_Raycaster"
        geometry={nodes.Slipper_1_Fourth_Hover_Raycaster.geometry}
        material={nodes.Slipper_1_Fourth_Hover_Raycaster.material}
        position={[-2.116, 0.526, -1.638]}
      />
      <mesh
        name="Slipper_2_Fourth_Hover_Raycaster"
        geometry={nodes.Slipper_2_Fourth_Hover_Raycaster.geometry}
        material={nodes.Slipper_2_Fourth_Hover_Raycaster.material}
        position={[-2.733, 0.524, -2.42]}
      />
      <mesh
        name="Coffee_Mug_Fourth_Raycaster_Hover"
        geometry={nodes.Coffee_Mug_Fourth_Raycaster_Hover.geometry}
        material={nodes.Coffee_Mug_Fourth_Raycaster_Hover.material}
        position={[-1.593, 3.091, -0.267]}
      />
      <mesh
        name="Poro_Raycaster_Hover_Fourth"
        geometry={nodes.Poro_Raycaster_Hover_Fourth.geometry}
        material={nodes.Poro_Raycaster_Hover_Fourth.material}
        position={[-2.648, 3.474, -0.843]}
      />
      <mesh
        name="MrRabbit_Fourth_Raycaster_Hover"
        geometry={nodes.MrRabbit_Fourth_Raycaster_Hover.geometry}
        material={nodes.MrRabbit_Fourth_Raycaster_Hover.material}
        position={[-2.646, 3.461, -2.252]}
      />
      <mesh
        name="MrRabbit_Son_Raycaster_Fourth_Hover"
        geometry={nodes.MrRabbit_Son_Raycaster_Fourth_Hover.geometry}
        material={nodes.MrRabbit_Son_Raycaster_Fourth_Hover.material}
        position={[-2.706, 3.465, -2.01]}
      />
      <mesh
        name="Seaweed_1_Hover_Third_Raycaster"
        geometry={nodes.Seaweed_1_Hover_Third_Raycaster.geometry}
        material={nodes.Seaweed_1_Hover_Third_Raycaster.material}
        position={[3.328, -0.6, -4.308]}
      />
      <mesh
        name="Seaweed_2_Hover_Third_Raycaster"
        geometry={nodes.Seaweed_2_Hover_Third_Raycaster.geometry}
        material={nodes.Seaweed_2_Hover_Third_Raycaster.material}
        position={[3.191, -0.672, -3.041]}
      />
      <mesh
        name="Seaweed_3_Hover_Third_Raycaster"
        geometry={nodes.Seaweed_3_Hover_Third_Raycaster.geometry}
        material={nodes.Seaweed_3_Hover_Third_Raycaster.material}
        position={[3.245, -0.453, -3.609]}
      />
      <mesh
        name="Seaweed_4_Hover_Third_Raycaster"
        geometry={nodes.Seaweed_4_Hover_Third_Raycaster.geometry}
        material={nodes.Seaweed_4_Hover_Third_Raycaster.material}
        position={[3.544, -0.541, -1.235]}
      />
      <mesh
        name="Seaweed_5_Hover_Third_Raycaster"
        geometry={nodes.Seaweed_5_Hover_Third_Raycaster.geometry}
        material={nodes.Seaweed_5_Hover_Third_Raycaster.material}
        position={[2.952, -0.777, 2.205]}
      />
      <mesh
        name="Seaweed_6_Hover_Third_Raycaster"
        geometry={nodes.Seaweed_6_Hover_Third_Raycaster.geometry}
        material={nodes.Seaweed_6_Hover_Third_Raycaster.material}
        position={[2.445, -0.436, 2.491]}
      />
      <mesh
        name="Seaweed_7_Hover_Third_Raycaster"
        geometry={nodes.Seaweed_7_Hover_Third_Raycaster.geometry}
        material={nodes.Seaweed_7_Hover_Third_Raycaster.material}
        position={[1.957, -0.561, 2.609]}
      />
      <mesh
        name="Seaweed_8_Hover_Third_Raycaster"
        geometry={nodes.Seaweed_8_Hover_Third_Raycaster.geometry}
        material={nodes.Seaweed_8_Hover_Third_Raycaster.material}
        position={[-0.964, -0.514, 2.937]}
      />
      <mesh
        name="Seaweed_9_Hover_Third_Raycaster"
        geometry={nodes.Seaweed_9_Hover_Third_Raycaster.geometry}
        material={nodes.Seaweed_9_Hover_Third_Raycaster.material}
        position={[-1.363, -0.209, 2.506]}
      />
      <mesh
        name="Seaweed_10_Hover_Third_Raycaster"
        geometry={nodes.Seaweed_10_Hover_Third_Raycaster.geometry}
        material={nodes.Seaweed_10_Hover_Third_Raycaster.material}
        position={[-2.686, -0.358, 2.679]}
      />
      <mesh
        name="Seaweed_11_Hover_Third_Raycaster"
        geometry={nodes.Seaweed_11_Hover_Third_Raycaster.geometry}
        material={nodes.Seaweed_11_Hover_Third_Raycaster.material}
        position={[-3.316, 0.03, 2.684]}
      />
      <mesh
        name="Seaweed_12_Hover_Third_Raycaster"
        geometry={nodes.Seaweed_12_Hover_Third_Raycaster.geometry}
        material={nodes.Seaweed_12_Hover_Third_Raycaster.material}
        position={[-3.436, -0.722, 3.086]}
      />
      <mesh
        name="Microphone_Hover_Third_Raycaster"
        geometry={nodes.Microphone_Hover_Third_Raycaster.geometry}
        material={nodes.Microphone_Hover_Third_Raycaster.material}
        position={[2.353, 2.837, -3.837]}
      />
      <mesh
        name="Box_1_Hover_Fourth_Raycaster"
        geometry={nodes.Box_1_Hover_Fourth_Raycaster.geometry}
        material={nodes.Box_1_Hover_Fourth_Raycaster.material}
        position={[-2.565, 0.827, -0.576]}
      />
      <mesh
        name="Box_2_Hover_Fourth_Raycaster"
        geometry={nodes.Box_2_Hover_Fourth_Raycaster.geometry}
        material={nodes.Box_2_Hover_Fourth_Raycaster.material}
        position={[-2.449, 1.389, -0.566]}
      />
      <mesh
        name="Box_3_Hover_Fourth_Raycaster"
        geometry={nodes.Box_3_Hover_Fourth_Raycaster.geometry}
        material={nodes.Box_3_Hover_Fourth_Raycaster.material}
        position={[-2.384, 1.809, -0.536]}
      />
      <mesh
        name="Rock_1_Third_Raycaster_Hover"
        geometry={nodes.Rock_1_Third_Raycaster_Hover.geometry}
        material={nodes.Rock_1_Third_Raycaster_Hover.material}
        position={[2.364, -1.337, -6.425]}
      />
      <mesh
        name="Rock_2_Third_Raycaster_Hover"
        geometry={nodes.Rock_2_Third_Raycaster_Hover.geometry}
        material={nodes.Rock_2_Third_Raycaster_Hover.material}
        position={[3.713, -0.808, -2.355]}
      />
      <mesh
        name="Rock_3_Third_Raycaster_Hover"
        geometry={nodes.Rock_3_Third_Raycaster_Hover.geometry}
        material={nodes.Rock_3_Third_Raycaster_Hover.material}
        position={[4.45, -1.075, 0.484]}
      />
      <mesh
        name="Rock_4_Third_Raycaster_Hover"
        geometry={nodes.Rock_4_Third_Raycaster_Hover.geometry}
        material={nodes.Rock_4_Third_Raycaster_Hover.material}
        position={[3.51, -0.879, 0.491]}
      />
      <mesh
        name="Rock_5_Third_Raycaster_Hover"
        geometry={nodes.Rock_5_Third_Raycaster_Hover.geometry}
        material={nodes.Rock_5_Third_Raycaster_Hover.material}
        position={[0.121, -0.797, 2.686]}
      />
      <mesh
        name="Rock_6_Third_Raycaster_Hover"
        geometry={nodes.Rock_6_Third_Raycaster_Hover.geometry}
        material={nodes.Rock_6_Third_Raycaster_Hover.material}
        position={[-2.107, -0.813, 3.139]}
      />
      <mesh
        name="Rock_7_Third_Raycaster_Hover"
        geometry={nodes.Rock_7_Third_Raycaster_Hover.geometry}
        material={nodes.Rock_7_Third_Raycaster_Hover.material}
        position={[-5.323, -1.171, 1.8]}
      />
      <mesh
        name="Frame_1_Second_Raycaster_Hover"
        geometry={nodes.Frame_1_Second_Raycaster_Hover.geometry}
        material={nodes.Frame_1_Second_Raycaster_Hover.material}
        position={[-2.841, 5.948, 1.333]}
      />
      <mesh
        name="Frame_2_Second_Raycaster_Hover"
        geometry={nodes.Frame_2_Second_Raycaster_Hover.geometry}
        material={nodes.Frame_2_Second_Raycaster_Hover.material}
        position={[-2.934, 5.787, 0.523]}
      />
      <mesh
        name="Frame_3_Second_Raycaster_Hover"
        geometry={nodes.Frame_3_Second_Raycaster_Hover.geometry}
        material={nodes.Frame_3_Second_Raycaster_Hover.material}
        position={[-2.907, 4.858, 0.879]}
      />
      <mesh
        name="Cactus_Raycaster_Fourth_Hover"
        geometry={nodes.Cactus_Raycaster_Fourth_Hover.geometry}
        material={nodes.Cactus_Raycaster_Fourth_Hover.material}
        position={[-2.914, 4.847, 0.201]}
      />
      <mesh
        name="Flower_Basket_Raycaster_Hover_Fourth"
        geometry={nodes.Flower_Basket_Raycaster_Hover_Fourth.geometry}
        material={nodes.Flower_Basket_Raycaster_Hover_Fourth.material}
        position={[-2.174, 2.283, 1.114]}
      />
      <mesh
        name="Headphones_Fourth_Raycaster_Hover"
        geometry={nodes.Headphones_Fourth_Raycaster_Hover.geometry}
        material={nodes.Headphones_Fourth_Raycaster_Hover.material}
        position={[-2.123, 3.079, 0.258]}
      />
      <mesh
        name="Mouth_Raycaster_Hover_Fourth"
        geometry={nodes.Mouth_Raycaster_Hover_Fourth.geometry}
        material={nodes.Mouth_Raycaster_Hover_Fourth.material}
        position={[-1.859, 3.161, -2.705]}
      />
      <mesh
        name="Keyboard_1_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_1_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_1_Fourth_Raycaster_Hover.material}
        position={[-2.027, 3.247, -1.134]}
      />
      <mesh
        name="Keyboard_2_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_2_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_2_Fourth_Raycaster_Hover.material}
        position={[-2.027, 3.247, -1.342]}
      />
      <mesh
        name="Keyboard_3_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_3_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_3_Fourth_Raycaster_Hover.material}
        position={[-2.027, 3.247, -1.549]}
      />
      <mesh
        name="Keyboard_4_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_4_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_4_Fourth_Raycaster_Hover.material}
        position={[-2.027, 3.247, -1.756]}
      />
      <mesh
        name="Keyboard_5_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_5_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_5_Fourth_Raycaster_Hover.material}
        position={[-2.027, 3.247, -1.963]}
      />
      <mesh
        name="Keyboard_6_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_6_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_6_Fourth_Raycaster_Hover.material}
        position={[-1.912, 3.243, -1.134]}
      />
      <mesh
        name="Keyboard_7_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_7_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_7_Fourth_Raycaster_Hover.material}
        position={[-1.912, 3.243, -1.342]}
      />
      <mesh
        name="Keyboard_8_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_8_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_8_Fourth_Raycaster_Hover.material}
        position={[-1.912, 3.243, -1.549]}
      />
      <mesh
        name="Keyboard_9_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_9_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_9_Fourth_Raycaster_Hover.material}
        position={[-1.912, 3.243, -1.756]}
      />
      <mesh
        name="Keyboard_10_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_10_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_10_Fourth_Raycaster_Hover.material}
        position={[-1.912, 3.243, -1.963]}
      />
      <mesh
        name="Keyboard_11_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_11_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_11_Fourth_Raycaster_Hover.material}
        position={[-1.796, 3.239, -1.134]}
      />
      <mesh
        name="Keyboard_12_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_12_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_12_Fourth_Raycaster_Hover.material}
        position={[-1.796, 3.239, -1.342]}
      />
      <mesh
        name="Keyboard_13_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_13_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_13_Fourth_Raycaster_Hover.material}
        position={[-1.796, 3.239, -1.549]}
      />
      <mesh
        name="Keyboard_14_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_14_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_14_Fourth_Raycaster_Hover.material}
        position={[-1.796, 3.239, -1.756]}
      />
      <mesh
        name="Keyboard_15_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_15_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_15_Fourth_Raycaster_Hover.material}
        position={[-1.796, 3.239, -1.963]}
      />
      <mesh
        name="Keyboard_16_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_16_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_16_Fourth_Raycaster_Hover.material}
        position={[-1.681, 3.235, -1.134]}
      />
      <mesh
        name="Keyboard_17_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_17_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_17_Fourth_Raycaster_Hover.material}
        position={[-1.681, 3.235, -1.342]}
      />
      <mesh
        name="Keyboard_18_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_18_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_18_Fourth_Raycaster_Hover.material}
        position={[-1.681, 3.235, -1.549]}
      />
      <mesh
        name="Keyboard_19_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_19_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_19_Fourth_Raycaster_Hover.material}
        position={[-1.681, 3.235, -1.756]}
      />
      <mesh
        name="Keyboard_20_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_20_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_20_Fourth_Raycaster_Hover.material}
        position={[-1.681, 3.235, -1.963]}
      />
      <mesh
        name="Keyboard_21_Fourth_Raycaster_Hover"
        geometry={nodes.Keyboard_21_Fourth_Raycaster_Hover.geometry}
        material={nodes.Keyboard_21_Fourth_Raycaster_Hover.material}
        position={[-1.541, 3.235, -1.54]}
      />
      <mesh
        name="Book_1_Fourth"
        geometry={nodes.Book_1_Fourth.geometry}
        material={nodes.Book_1_Fourth.material}
        position={[-2.449, 4.369, -3.614]}
      />
      <mesh
        name="Book_2_Fourth"
        geometry={nodes.Book_2_Fourth.geometry}
        material={nodes.Book_2_Fourth.material}
        position={[-2.449, 4.369, -3.614]}
      />
      <mesh
        name="Pencil_Holder_Fourth"
        geometry={nodes.Pencil_Holder_Fourth.geometry}
        material={nodes.Pencil_Holder_Fourth.material}
        position={[-2.449, 4.369, -3.614]}
      />
      <mesh
        name="First"
        geometry={nodes.First.geometry}
        material={nodes.First.material}
        position={[-2.85, 5.862, -2.681]}
      />
      <mesh
        name="Second"
        geometry={nodes.Second.geometry}
        material={nodes.Second.material}
        position={[-2.85, 5.862, -2.681]}
      />
      <mesh
        name="Third"
        geometry={nodes.Third.geometry}
        material={nodes.Third.material}
        position={[-0.383, -0.517, -1.129]}
      />
      <mesh
        name="Fourth"
        geometry={nodes.Fourth.geometry}
        material={nodes.Fourth.material}
        position={[-2.449, 4.369, -3.614]}
      />
    </group>
  );
}

useGLTF.preload("/main_room.glb");
